name: fitnessapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  youtube_player_iframe: ^4.0.4

  video_player: ^2.8.2
  chewie: ^1.7.4
  firebase_core: ^3.9.0
  firebase_storage: ^12.3.0

  pedometer: ^4.0.2
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  fl_chart: ^0.65.0
  intl: ^0.19.0
  http: ^1.2.2
  percent_indicator: ^4.2.3
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.8
  url_launcher: ^6.2.5
  image_picker: ^1.0.7
  font_awesome_flutter: ^10.7.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true



